
import "@/app/assest/css/globals.css";
export const metadata = {
  title: "Personal App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
